name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção da Imagem Docker
        run: echo "Executando o comando Docker Build"

      - name: Construção e envio da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            rafaelbiasotto/fake-shop:latest
            rafaelbiasotto/fake-shop:v${{ github.run_number}}

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

        on: [push]

      - name: Run Azure Login With a Service Principal Secret

      jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
      

